export const PERMISSIONS = {
  companyUpdateProfile: "company:update_profile",
  companyReadUsers: "company:read_users",
  companyCreateUser: "company:create_user",
  companyDeleteUser: "company:delete_user",
  companyRoleRead: "company:role_read",
  companyRoleAssign: "company:role_assign",
  routeRead: "route:read",
  routeCreate: "route:create",
  routeAddStop: "route:add_stop",
  routeActivate: "route:activate",
  routeDeactivate: "route:deactivate",
  scheduleRead: "schedule:read",
  scheduleCreate: "schedule:create",
  scheduleUpdate: "schedule:update",
  scheduleCancel: "schedule:cancel",
  busRead: "bus:read",
  busCreate: "bus:create",
  busUpdate: "bus:update",
  driverRead: "driver:read",
  driverCreate: "driver:create",
  driverUpdate: "driver:update",
  taskCreate: "task:create",
  // Balcão e embarque (endpoints /boarding/* + venda ao balcão). Cada operação
  // tem o seu código — dá para ter uma bilheteira só com `booking:sell`, um
  // fiscal só com `boarding:validate`/`boarding:record`, etc.
  bookingSell: "booking:sell",
  boardingReadSchedules: "boarding:read_schedules",
  boardingValidate: "boarding:validate",
  boardingRecord: "boarding:record",
  financeReportDaily: "finance:report_daily",
  paymentReadCompany: "payment:read_company",
  paymentReadAll: "payment:read_all",
  paymentConfirm: "payment:confirm",
  adminCompanyPending: "admin:company_pending",
  adminCompanyReadAll: "admin:company_read_all",
  adminCompanyApprove: "admin:company_approve",
  adminCompanyReject: "admin:company_reject",
  adminCompanySuspend: "admin:company_suspend",
  adminUserReadAll: "admin:user_read_all",
  adminAuditRead: "admin:audit_read",
  adminPermissionRead: "admin:permission_read",
  adminRoleRead: "admin:role_read",
  adminRoleCreate: "admin:role_create",
  adminRoleUpdate: "admin:role_update",
  adminRoleDelete: "admin:role_delete",
  adminRoleAssign: "admin:role_assign",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
